export type ActorType = 'ai' | 'human'
export type AuditAction =
  | 'regulation_detected'
  | 'policy_gap_identified'
  | 'recommendation_generated'
  | 'task_assigned'
  | 'task_accepted'
  | 'task_rejected'
  | 'task_reassigned'
  | 'detail_requested'
  | 'policy_updated'
  | 'policy_version_created'
  | 'task_status_changed'

export interface AuditEvent {
  id: string
  timestamp: string
  actorId: string | 'AI'
  actorType: ActorType
  action: AuditAction
  actionLabel: string
  target: string
  targetId: string
  detail: string
  overrideReason?: string
}

export const auditLog: AuditEvent[] = [
  {
    id: 'audit-001',
    timestamp: '2026-05-16T09:00:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'regulation_detected',
    actionLabel: 'Regulation detected',
    target: 'FinCEN Notice 2026-04',
    targetId: 'reg-001',
    detail: 'New regulatory publication detected from FinCEN RSS feed and official website. Classified as critical severity based on penalty exposure and compliance deadline proximity.',
  },
  {
    id: 'audit-002',
    timestamp: '2026-05-16T09:05:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'policy_gap_identified',
    actionLabel: 'Policy gap identified',
    target: 'Beneficial Ownership Verification Procedure',
    targetId: 'pol-003',
    detail: 'AI identified gap: current policy states 25% ownership threshold; FinCEN Notice 2026-04 requires 10%. Confidence score: 0.97. Additional gap: 24-hour update requirement not addressed.',
  },
  {
    id: 'audit-003',
    timestamp: '2026-05-16T09:06:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'recommendation_generated',
    actionLabel: 'Recommendation generated',
    target: 'Task: Lower BOV threshold from 25% to 10%',
    targetId: 'task-001',
    detail: 'AI generated policy amendment recommendation with 3 citations to §2.1, §2.3(a), §4.2(b)(iii) of FinCEN Notice 2026-04. Suggested owner: Marcus Webb. Proposed deadline: 2026-06-20.',
  },
  {
    id: 'audit-004',
    timestamp: '2026-05-16T09:07:00Z',
    actorId: 'user-001',
    actorType: 'human',
    action: 'task_assigned',
    actionLabel: 'Task assigned',
    target: 'Marcus Webb',
    targetId: 'task-001',
    detail: 'Sarah Chen accepted AI\'s suggested assignment. Task assigned to Marcus Webb with deadline 2026-06-20.',
  },
  {
    id: 'audit-005',
    timestamp: '2026-05-17T10:30:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'regulation_detected',
    actionLabel: 'Regulation detected',
    target: 'NYDFS Part 500 Amendment 2026',
    targetId: 'reg-012',
    detail: 'New regulatory publication detected from NYDFS regulatory update feed. Classified as critical severity based on June 30, 2026 deadline.',
  },
  {
    id: 'audit-006',
    timestamp: '2026-05-17T10:33:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'policy_gap_identified',
    actionLabel: 'Policy gap identified',
    target: 'MFA and Privileged Access Policy',
    targetId: 'pol-015',
    detail: 'AI identified gap: current policy lists SMS OTP as acceptable MFA. NYDFS §500.12(b) prohibits SMS OTP effective June 30, 2026. Confidence score: 0.99.',
  },
  {
    id: 'audit-007',
    timestamp: '2026-05-17T10:35:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'recommendation_generated',
    actionLabel: 'Recommendation generated',
    target: 'Task: Replace SMS OTP with phishing-resistant MFA',
    targetId: 'task-002',
    detail: 'AI generated policy amendment recommendation with 3 citations to §500.12(b), §500.12(a), §500.12(e) of NYDFS Part 500 Amendment.',
  },
  {
    id: 'audit-008',
    timestamp: '2026-05-17T14:22:00Z',
    actorId: 'user-004',
    actorType: 'human',
    action: 'detail_requested',
    actionLabel: 'More detail requested',
    target: 'Task: Replace SMS OTP with phishing-resistant MFA',
    targetId: 'task-002',
    detail: 'James O\'Brien requested additional AI guidance on implementation timeline for hardware security key rollout.',
  },
  {
    id: 'audit-009',
    timestamp: '2026-05-17T14:25:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'recommendation_generated',
    actionLabel: 'Follow-up recommendation',
    target: 'Task: Replace SMS OTP with phishing-resistant MFA',
    targetId: 'task-002',
    detail: 'AI provided follow-up guidance on phased MFA implementation: prioritize privileged accounts by June 10, remote access by June 20, standard accounts by June 30.',
  },
  {
    id: 'audit-010',
    timestamp: '2026-05-18T08:00:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'regulation_detected',
    actionLabel: 'Regulation detected',
    target: 'EU AI Act Article 14 Amendment',
    targetId: 'reg-002',
    detail: 'New regulatory publication detected from EU Official Journal. Classified as high severity. Implementation deadline: August 6, 2026.',
  },
  {
    id: 'audit-011',
    timestamp: '2026-05-18T08:12:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'policy_gap_identified',
    actionLabel: 'Policy gap identified',
    target: 'AI System Risk Assessment Framework',
    targetId: 'pol-007',
    detail: 'AI identified 3 gaps: (1) override authority without management approval not addressed; (2) 30-minute explanation deadline missing; (3) 36-month audit log retention not specified.',
  },
  {
    id: 'audit-012',
    timestamp: '2026-05-18T08:15:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'recommendation_generated',
    actionLabel: 'Recommendation generated',
    target: 'Task: Add EU AI Act human oversight documentation',
    targetId: 'task-003',
    detail: 'AI generated policy amendment recommendation with citations to §14.2(a), §14.3(d), §14.5 of EU AI Act Article 14.',
  },
  {
    id: 'audit-013',
    timestamp: '2026-05-19T09:15:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'regulation_detected',
    actionLabel: 'Regulation detected',
    target: 'DORA ITS 2026-07',
    targetId: 'reg-010',
    detail: 'New regulatory publication detected from EBA regulatory feed. Classified as high severity. Implementation deadline: August 17, 2026.',
  },
  {
    id: 'audit-014',
    timestamp: '2026-05-19T11:00:00Z',
    actorId: 'user-004',
    actorType: 'human',
    action: 'task_status_changed',
    actionLabel: 'Task moved to in review',
    target: 'Task: Add DORA major incident notification procedure',
    targetId: 'task-005',
    detail: 'James O\'Brien moved task from New to In Review after initial assessment.',
  },
  {
    id: 'audit-015',
    timestamp: '2026-05-20T10:00:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'regulation_detected',
    actionLabel: 'Regulation detected',
    target: 'PDPA Amendment Act 2026',
    targetId: 'reg-013',
    detail: 'New regulatory publication detected from PDPC website. Classified as medium severity.',
  },
  {
    id: 'audit-016',
    timestamp: '2026-05-20T10:05:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'policy_gap_identified',
    actionLabel: 'Policy gap identified',
    target: 'Customer Data Retention Policy',
    targetId: 'pol-001',
    detail: 'AI identified gap: cross-border data transfer section does not address Transfer Impact Assessment requirement for elevated-risk jurisdictions.',
  },
  {
    id: 'audit-017',
    timestamp: '2026-05-21T11:00:00Z',
    actorId: 'user-003',
    actorType: 'human',
    action: 'detail_requested',
    actionLabel: 'More detail requested',
    target: 'Task: Add biometric data DPIA requirement',
    targetId: 'task-006',
    detail: 'Priya Sharma asked for clarification on the scope of the DPIA obligation for existing biometric deployments.',
  },
  {
    id: 'audit-018',
    timestamp: '2026-05-21T11:05:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'recommendation_generated',
    actionLabel: 'Follow-up recommendation',
    target: 'Task: Add biometric data DPIA requirement',
    targetId: 'task-006',
    detail: 'AI clarified that §3.1 of EDPB Guidelines 2026/03 explicitly extends the DPIA obligation to existing deployments without a prior DPIA as of the Guidelines effective date.',
  },
  {
    id: 'audit-019',
    timestamp: '2026-05-22T09:00:00Z',
    actorId: 'user-006',
    actorType: 'human',
    action: 'task_status_changed',
    actionLabel: 'Task moved to awaiting human',
    target: 'Task: Expand climate disclosure — Scope 3 attestation',
    targetId: 'task-007',
    detail: 'David Kim escalated to awaiting human review — requires CFO sign-off before policy change given financial reporting implications.',
  },
  {
    id: 'audit-020',
    timestamp: '2026-05-23T14:00:00Z',
    actorId: 'user-002',
    actorType: 'human',
    action: 'detail_requested',
    actionLabel: 'More detail requested',
    target: 'Task: Lower BOV threshold from 25% to 10%',
    targetId: 'task-001',
    detail: 'Marcus Webb requested AI clarification on indirect ownership calculation methodology for trust structures.',
  },
  {
    id: 'audit-021',
    timestamp: '2026-05-23T14:08:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'recommendation_generated',
    actionLabel: 'Follow-up recommendation',
    target: 'Task: Lower BOV threshold from 25% to 10%',
    targetId: 'task-001',
    detail: 'AI provided guidance on trust beneficial ownership analysis under FinCEN Notice 2026-04 including trustee, beneficiary, and settlor identification requirements.',
  },
  {
    id: 'audit-022',
    timestamp: '2026-05-24T10:00:00Z',
    actorId: 'user-002',
    actorType: 'human',
    action: 'task_accepted',
    actionLabel: 'Recommendation accepted',
    target: 'Task: Travel rule compliance for DPT',
    targetId: 'task-011',
    detail: 'Marcus Webb accepted AI recommendation and applied policy update. Policy version 5.1 created.',
  },
  {
    id: 'audit-023',
    timestamp: '2026-05-24T10:15:00Z',
    actorId: 'user-002',
    actorType: 'human',
    action: 'policy_version_created',
    actionLabel: 'Policy version created',
    target: 'AML Transaction Monitoring SOP',
    targetId: 'pol-002',
    detail: 'Version 5.1 created incorporating MAS Notice 626 Travel Rule requirements for DPT transfers.',
  },
  {
    id: 'audit-024',
    timestamp: '2026-05-25T09:00:00Z',
    actorId: 'user-003',
    actorType: 'human',
    action: 'task_accepted',
    actionLabel: 'Recommendation accepted',
    target: 'Task: Data portability fulfillment procedure',
    targetId: 'task-009',
    detail: 'Priya Sharma accepted AI recommendation. Policy update applied to Privacy Notice and Consent Management Policy.',
  },
  {
    id: 'audit-025',
    timestamp: '2026-05-25T09:20:00Z',
    actorId: 'user-003',
    actorType: 'human',
    action: 'policy_version_created',
    actionLabel: 'Policy version created',
    target: 'Privacy Notice and Consent Management Policy',
    targetId: 'pol-012',
    detail: 'Version 2.9 created incorporating PIPEDA data portability requirements.',
  },
  {
    id: 'audit-026',
    timestamp: '2026-05-26T14:00:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'regulation_detected',
    actionLabel: 'Regulation detected',
    target: 'PRA Consultation Paper CP5/26',
    targetId: 'reg-016',
    detail: 'New regulatory publication detected from PRA website. Classified as medium severity. Applies to UK subsidiary operations.',
  },
  {
    id: 'audit-027',
    timestamp: '2026-05-27T10:00:00Z',
    actorId: 'user-004',
    actorType: 'human',
    action: 'task_rejected',
    actionLabel: 'Recommendation rejected',
    target: 'Task: Add DORA major incident notification procedure',
    targetId: 'task-005',
    detail: 'James O\'Brien rejected initial recommendation. Override reason recorded.',
    overrideReason: 'The proposed edit conflates the 15-minute internal escalation to CISO with the 4-hour regulatory notification to the competent authority. These are separate obligations with different triggers. The policy must distinguish them clearly before I can accept. Requesting revised recommendation with explicit delineation.',
  },
  {
    id: 'audit-028',
    timestamp: '2026-05-27T10:10:00Z',
    actorId: 'AI',
    actorType: 'ai',
    action: 'recommendation_generated',
    actionLabel: 'Revised recommendation generated',
    target: 'Task: Add DORA major incident notification procedure',
    targetId: 'task-005',
    detail: 'AI generated revised recommendation with clearer delineation between internal escalation (15 min to CISO) and regulatory notification (4 hours to competent authority).',
  },
  {
    id: 'audit-029',
    timestamp: '2026-05-28T11:00:00Z',
    actorId: 'user-005',
    actorType: 'human',
    action: 'task_status_changed',
    actionLabel: 'Task moved to in review',
    target: 'Task: Add FCA vulnerable customer quarterly monitoring',
    targetId: 'task-010',
    detail: 'Rachel Novak started review of FCA Consumer Duty task.',
  },
  {
    id: 'audit-030',
    timestamp: '2026-05-29T16:00:00Z',
    actorId: 'user-001',
    actorType: 'human',
    action: 'task_reassigned',
    actionLabel: 'Task reassigned',
    target: 'Task: Operational resilience scenario testing for DORA',
    targetId: 'task-012',
    detail: 'Sarah Chen reassigned task from James O\'Brien to herself given board-level reporting implications.',
  },
]
